server:
  port: 8083

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  config:
    import: classpath:application-secret.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
